# Generated by Django 4.2.7 on 2025-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': []},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('owner', 'ConcertOwner')], max_length=20),
        ),
    ]
