# Generated by Django 4.2.7 on 2025-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concertowner',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='concertowner',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
