# Generated by Django 5.1.4 on 2025-04-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_artist_followers_alter_artist_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Recommandation',
        ),
    ]
