COUNTRY_CODE = {
    'AT': 'Austria',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'EE': 'Estonia',
    'FI': 'Finland',
    'FR': 'France',
    'DE': 'Germany',
    'GR': 'Greece',
    'HU': 'Hungary',
    'IE': 'Ireland',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'NL': 'Netherlands',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'SK': 'Slovakia',
    'ES': 'Spain',
    'SE': 'Sweden'
}

GENRE_MAPPING = {
    "slug": "country",  
    "rap_hip_hop": "Rap/Hip Hop",
    "pop": "Pop",
    "electro": "Electro",
    "rnb": "R&B",
    "films_jeux_video": "Films/Jeux vidéo",
    "rock_hard_rock": "Rock/Hard Rock",
    "techno_house": "Techno/House",
    "country_music": "Country",
    "trance": "Trance",
    "reggae": "Reggae",
    "population_total": "population_total",
    "life_expectancy": "life_expectancy",
    "birth_rate": "birth_rate",
    "avg_income": "avg_income"
} 